# CompileShader.cmake
#
# Converts a SPIR-V binary into a C++ header containing a constexpr u32 array.
#
# Expected variables (passed via -D):
#   INPUT_SPV  — path to the .spv binary
#   OUTPUT_HPP — path to write the generated header
#   ARRAY_NAME — name for the constexpr u32 array

if (NOT EXISTS "${INPUT_SPV}")
    message(FATAL_ERROR "SPIR-V file not found: ${INPUT_SPV}")
endif ()

file(READ "${INPUT_SPV}" SPV_HEX HEX)

# SPIR-V is a stream of little-endian 32-bit words.
# file(READ HEX) gives sequential bytes, so we reverse each
# group of 4 bytes to produce the correct u32 literal.
string(LENGTH "${SPV_HEX}" HEX_LENGTH)
math(EXPR WORD_COUNT "${HEX_LENGTH} / 8")

set(WORDS "")
set(COLUMN 0)

math(EXPR LAST_INDEX "${WORD_COUNT} - 1")
foreach (I RANGE 0 ${LAST_INDEX})
    math(EXPR OFFSET "${I} * 8")

    math(EXPR B0 "${OFFSET} + 0")
    math(EXPR B1 "${OFFSET} + 2")
    math(EXPR B2 "${OFFSET} + 4")
    math(EXPR B3 "${OFFSET} + 6")

    string(SUBSTRING "${SPV_HEX}" ${B3} 2 BYTE3)
    string(SUBSTRING "${SPV_HEX}" ${B2} 2 BYTE2)
    string(SUBSTRING "${SPV_HEX}" ${B1} 2 BYTE1)
    string(SUBSTRING "${SPV_HEX}" ${B0} 2 BYTE0)

    set(WORD "0x${BYTE3}${BYTE2}${BYTE1}${BYTE0}")

    if (COLUMN EQUAL 0)
        string(APPEND WORDS "    ")
    endif ()

    string(APPEND WORDS "${WORD},")
    math(EXPR COLUMN "(${COLUMN} + 1) % 6")

    if (COLUMN EQUAL 0)
        string(APPEND WORDS "\n")
    else ()
        string(APPEND WORDS " ")
    endif ()
endforeach ()

string(STRIP "${WORDS}" WORDS)

set(HEADER
        "// Generated by CompileShader.cmake
#pragma once

#include \"Common/Types.hpp\"

namespace Anvil::Shaders
{
  static constexpr u32 ${ARRAY_NAME}[] = {
${WORDS}
  };

  static constexpr u32 ${ARRAY_NAME}Size = sizeof( ${ARRAY_NAME} );
} // namespace Anvil::Shaders
")

file(WRITE "${OUTPUT_HPP}" "${HEADER}")